# Import Data

In [3]:
import pandas as pd
import numpy as np

In [4]:
# Get data frame with all users for which there is general data
users = pd.read_csv("Users.csv")

In [5]:
print(users.columns)
users.head()

Index(['UserID', 'BirthYear', 'DA', 'DiagnosisYear', 'Gender', 'Impact',
       'Levadopa', 'MAOB', 'Other', 'Parkinsons', 'Sided', 'Tremors', 'UPDRS'],
      dtype='object')

,UserID,BirthYear,DA,DiagnosisYear,Gender,Impact,Levadopa,MAOB,Other,Parkinsons,Sided,Tremors,UPDRS
0,User_0EA27ICBLF,1952.0,True,2000,Female,Severe,True,False,False,True,Left,True,Don't know
1,User_0QAZFRHQHW,1959.0,False,------,Female,------,False,False,False,False,None,False,Don't know
2,User_0WTDIGPSBZ,1946.0,False,------,Female,------,False,False,False,False,None,False,Don't know
3,User_1HOEBIGASW,1944.0,False,------,Male,------,False,False,False,False,None,False,Don't know
4,User_1WMVCCU4RH,1953.0,False,2017,Male,Medium,False,False,False,True,Left,True,Don't know

# Modify DataFrame

Turn the DataFrame into more usable with all numbers. <br>
UserID: dropped first 5 digits, which are are only "User_" <br>
Parkinsons: 1 for diagnosed with Parkinsons, 0 for not <br>
DA: 1 for using, 0 for not <br>
Levadopa: 1 for using, 0 for not <br>
MAOB: 1 for using, 0 for not <br>
Other: 1 for using, 0 for not <br>
Gender: 1 for female, 0 for male <br>
Tremors: 1 for yes, 0 for no <br>
Impact: 0 - 3 for not applicable, mild, medium, severe <br>
Sided: 0 for none, 1 for left, 2 for right <br>
UPDRS: 0 for unknown, then 1-5 on scale <br>

In [6]:
# Modify the data frame to be more usable
conditions = [
    (users['Impact'] == ' Mild'),
    (users['Impact'] == ' Medium'),
    (users['Impact'] == ' Severe'),
    (users['Impact'] != ' Mild') & (users['Impact'] != ' Medium') & (users['Impact'] != 'Severe')
    ]
values = [1,2,3,0]

conditions1 = [
    (users['UPDRS'] == 'Don\'t know'), 
    (users['UPDRS'] == '1'),
    (users['UPDRS'] == '2'),
    (users['UPDRS'] == '3'),
    (users['UPDRS'] == '4'),
    (users['UPDRS'] == '5')
]
values1 = [0,1,2,3,4,5]

conditions2 = [
    (users['Sided'] == ' None'),
    (users['Sided'] == ' Left'),
    (users['Sided'] == ' Right'),
]
values2 = [0,1,2]


users['UserID'] = [e[5:] for e in users['UserID']]
users['Gender'] = np.where(users['Gender'] == ' Female', 1, 0)
users['Parkinsons'] = np.where(users['Parkinsons'] == ' True', 1, 0)
users['DA'] = np.where(users['DA'] == ' True', 1, 0)
users['Levadopa'] = np.where(users['Levadopa'] == ' True', 1, 0)
users['MAOB'] = np.where(users['MAOB'] == ' True', 1, 0)
users['Tremors'] = np.where(users['Tremors'] == ' True', 1, 0)
users['Impact'] = np.select(conditions, values)
users['Other'] = np.where(users['Other'] == ' True', 1, 0)
users['Sided'] = np.select(conditions2, values2)
users['UPDRS'] = np.select(conditions1, values1)
users['BirthYear'] = pd.to_numeric(users['BirthYear'], errors='coerce')
users['DiagnosisYear'] = pd.to_numeric(users['DiagnosisYear'], errors='coerce')

In [7]:
users.head(10)

,UserID,BirthYear,DA,DiagnosisYear,Gender,Impact,Levadopa,MAOB,Other,Parkinsons,Sided,Tremors,UPDRS
0,0EA27ICBLF,1952.0,1,2000.0,1,3,1,0,0,1,1,1,0
1,0QAZFRHQHW,1959.0,0,NaN,1,0,0,0,0,0,0,0,0
2,0WTDIGPSBZ,1946.0,0,NaN,1,0,0,0,0,0,0,0,0
3,1HOEBIGASW,1944.0,0,NaN,0,0,0,0,0,0,0,0,0
4,1WMVCCU4RH,1953.0,0,2017.0,0,2,0,0,0,1,1,1,0
5,1XNJCXS3EY,1936.0,0,NaN,0,0,0,0,0,0,0,0,0
6,2JTCBKUP8T,1958.0,0,2013.0,0,2,1,0,0,1,2,1,0
7,2X17VCRRQA,1951.0,0,2003.0,0,3,1,0,0,1,1,1,0
8,310NXPGJPD,1961.0,0,2015.0,1,2,1,0,1,1,1,1,0
9,39KQRZCESF,1942.0,1,2013.0,0,2,1,0,0,1,2,1,0

# Data Breakdown
Here, we examine how the participants break down into the various categories.

In [6]:
parkinsons = users[users['Parkinsons'] == 1]
none = users[users['Parkinsons'] == 0]
print("There are",len(parkinsons),"observations in the parkinsons df.")
print("There are",len(none),"observations in the none df.")

There are 169 observations in the parkinsons df.
There are 58 observations in the none df.

In [7]:
da = users[users['DA'] == 1]
no_da = users.drop(da.index)
print("There are",len(da),"people who take dopamine agonist.")
print("There are",len(no_da),"people who do not (including those without parkinsons).")

There are 33 people who take dopamine agonist.
There are 194 people who do not (including those without parkinsons).

In [8]:
lev = users[users['Levadopa'] == 1]
no_lev = users[users['Levadopa'] == 0]
print("There are",len(lev),"taking levadopa.")
print("There are",len(no_lev),"people who don't take levadopa")

There are 112 taking levadopa.
There are 115 people who don't take levadopa

In [9]:
mao = users[users['MAOB'] == 1]
no_mao = users[users['MAOB'] == 0]
print("There are",len(mao),"taking MAO-B inhibitor")
print("There are",len(no_mao),"people who don't take MAO-B inhibitor")

There are 15 taking MAO-B inhibitor
There are 212 people who don't take MAO-B inhibitor

In [9]:
oth = users[users['Other'] == 1]
no_oth = users[users['Other'] == 0]
print("There are",len(oth),"taking other medication")
print("There are",len(no_oth),"people who don't take other medication")

There are 69 taking other medication
There are 158 people who don't take other medication

In [10]:
med1 = parkinsons[parkinsons['Levadopa'] == 0]
med2 = med1[med1['DA'] == 0]
med3 = med2[med2['MAOB'] == 0]
med4 = med3[med3['Other'] == 0]
print("There are",len(med4),"with PD taking no medication")

There are 22 with PD taking no medication

In [11]:
severe = users[users['Impact'] == 2]
print(len(severe))

74

# Start Working with Tappy Files 
First, we find how many users we have that also have tappy data. Then, we isolate some parameters from the tappy data for each person.

In [8]:
import os

In [9]:
# Get people in the User Data
people_users = users['UserID'].tolist()

# Get people in Tappy Data
tappy_files = os.listdir('ArchivedData')
tappy_users = tappy_files
i = 0
for file in tappy_files:
    tappy_users[i] = file[:10]
    i = i + 1

# Isolate the users we want and make new Data Frame
all_users = set(people_users).intersection(tappy_users)
print(len(all_users))

usersA = users[users['UserID'].isin(all_users)]
usersA = usersA[(usersA['Parkinsons'] == 0) | ((usersA['Levadopa'] == 0) & (usersA['Impact'] == 1))]
print(len(usersA))
usersA = usersA.reset_index(drop = True)
usersA.head()

217
87

,UserID,BirthYear,DA,DiagnosisYear,Gender,Impact,Levadopa,MAOB,Other,Parkinsons,Sided,Tremors,UPDRS
0,0QAZFRHQHW,1959.0,0,NaN,1,0,0,0,0,0,0,0,0
1,1HOEBIGASW,1944.0,0,NaN,0,0,0,0,0,0,0,0,0
2,1XNJCXS3EY,1936.0,0,NaN,0,0,0,0,0,0,0,0,0
3,3DIXPRIOSW,1936.0,0,NaN,0,0,0,0,0,0,0,0,0
4,48DZPAJ5NS,1950.0,0,2010.0,0,1,0,0,1,1,0,0,0

In [8]:
from datetime import datetime

In [11]:
# Function creating proper data frame for a list of data files that in theory all correspond to same person
# Discard any times less than 0 or larger than 5 seconds
def extract_tappy_df(tappy_files):
    filesdf = [pd.read_csv('ArchivedData/' + file, delimiter = '\t', index_col = False, names = ['UserKey', 'Date', 'Timestamp', 'Hand', 'Hold time', 'Direction', 'Latency time', 'Flight time']) for file in tappy_files]
    files = filesdf
    # Transform data frame to be more usable, and get rid of bad rows
    for i in range(len(filesdf)):
        file = filesdf[i]
        file = file[(file['Hand'] == 'L') | (file['Hand'] == 'R')]
        file = file[(file['Direction'] == 'LL') | (file['Direction'] == 'LR') | (file['Direction'] == 'RL') | (file['Direction'] == 'RR')]
        date = file['Date']
        hold = file['Hold time']
        latency = file['Latency time']
        flight = file['Flight time']
        file['Date'] = pd.to_datetime(date, errors='coerce', format='%y%M%d').dt.date
        for column in ['Hold time', 'Latency time', 'Flight time']:
            file[column] = pd.to_numeric(file[column], errors = 'coerce')
        file = file.dropna(axis = 0)
        file = file[(file['Hold time'] > 0) & (file['Flight time'] > 0) & (file['Latency time'] > 0) & (file['Hold time'] < 9000) & (file['Flight time'] < 9000) & (file['Latency time'] < 9000)]
        #file = file[(file['Hold time'] > 0) & (file['Flight time'] > 0) & (file['Latency time'] > 0)]
        del file['Flight time']
        files[i] = file
    df = pd.concat(files)
    return df

In [41]:
# Function taking tappy data frame and extracting relevant features 
# Note those featurs are in flux
def extract_features(tappy_df):
    #Mean, Std, Skew, Kurtosis
    direction_group_mean = tappy_df.groupby('Direction').mean()
    direction_group_mean = direction_group_mean.reindex(['LL', 'LR', 'RL', 'RR'])
    direction_group_mean = direction_group_mean.sort_index()
    data_dir_mean = (direction_group_mean.values.flatten())
    direction_group_std = tappy_df.groupby('Direction').std()
    direction_group_std = direction_group_std.reindex(['LL', 'LR', 'RL', 'RR'])
    direction_group_std = direction_group_std.sort_index()
    data_dir_std = (direction_group_std.values.flatten())
    direction_group_skew = tappy_df.groupby('Direction').skew()
    direction_group_skew = direction_group_skew.reindex(['LL', 'LR', 'RL', 'RR'])
    direction_group_skew = direction_group_skew.sort_index()
    data_dir_skew = (direction_group_skew.values.flatten())
    direction_group_kurt = tappy_df.groupby('Direction').apply(pd.DataFrame.kurt)
    direction_group_kurt = direction_group_kurt.reindex(['LL', 'LR', 'RL', 'RR'])
    direction_group_kurt = direction_group_kurt.sort_index()
    data_dir_kurt = (direction_group_kurt.values.flatten())
    
    
    #Mean, Std, Skew, Kurtosis
    hand_group_mean = tappy_df.groupby('Hand').mean()
    hand_group_mean = hand_group_mean.reindex(['L', 'R'])
    hand_group_mean = hand_group_mean.sort_index()
    data_hand_mean = (hand_group_mean.values.flatten())
    hand_group_std = tappy_df.groupby('Hand').std()
    hand_group_std = hand_group_std.reindex(['L', 'R'])
    hand_group_std = hand_group_std.sort_index()
    data_hand_std = (hand_group_std.values.flatten())
    hand_group_skew = tappy_df.groupby('Hand').skew()
    hand_group_skew = hand_group_skew.reindex(['L', 'R'])
    hand_group_skew = hand_group_skew.sort_index()
    data_hand_skew = (hand_group_skew.values.flatten())
    hand_group_kurt = tappy_df.groupby('Hand').apply(pd.DataFrame.kurt)
    hand_group_kurt = hand_group_kurt.reindex(['L', 'R'])
    hand_group_kurt = hand_group_kurt.sort_index()
    data_hand_kurt = (hand_group_kurt.values.flatten())
    
    #Extra
    LR_hand_hold = data_hand_mean[0] - data_hand_mean[2]
    LL_RR_latency = data_dir_mean[1] - data_dir_mean[7]
    LR_RL_latency = data_dir_mean[3] - data_dir_mean[5]
    extra = np.array([LR_hand_hold, LL_RR_latency, LR_RL_latency])
    data = np.concatenate((data_dir_mean, data_dir_std, data_dir_skew, data_dir_kurt, data_hand_mean, data_hand_std, data_hand_skew, data_hand_kurt, extra), axis = 0)
    return data

In [42]:
# Function which given a user, returns an array of files associated to user
def get_user(user):
    filenames = os.listdir('ArchivedData')
    user_data = np.array([])
    for filename in filenames:
        if user in filename:
            user_data = np.append([filename], user_data)
    return user_data

In [43]:
# Various Cutoffs for user data
user_names = usersA['UserID']
LOW_CUTOFF = 500
MED_CUTOFF = 1000
HIGH_CUTOFF = 2000
for user in user_names: 
    files = get_user(user)
    tappy_data = extract_tappy_df(files)
    length = len(tappy_data)
    usersA['Length'] = length
usersB = usersA.copy()
usersC = usersA.copy()
usersD = usersA.copy()
usersB = usersB[usersB['Length'] > LOW_CUTOFF]
usersC = usersC[usersC['Length'] > MED_CUTOFF]
usersD = usersD[usersD['Length'] > HIGH_CUTOFF]
print(len(usersA))
print(len(usersB))
print(len(usersC))
print(len(usersD))
print(usersA['Length'].min())

/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (4,6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (4,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (1,4,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (4,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

87
87
87
87
28759

In [35]:
# Testing Code
file_name1 = '0EA27ICBLF_1607.txt'
file_name2 = '0EA27ICBLF_1608.txt'
tappy_data = extract_tappy_df([file_name1, file_name2])
tappy_info = extract_features(tappy_data)
print(tappy_data.dtypes)
print(extract_features(tappy_data))
print(type(tappy_info))
filenames = os.listdir('ArchivedData')
print(type(filenames))
print(len(filenames))
user = users['UserID'][0]
print(get_user(user))
print(len(tappy_data))

/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (4,6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

UserKey          object
Date             object
Timestamp        object
Hand             object
Hold time       float64
Direction        object
Latency time    float64
dtype: object
[ 8.21690398e+01  2.63586377e+02  8.19468100e+01  2.77610541e+02
  7.46711476e+01  4.16856331e+02  7.92945629e+01  2.73864624e+02
  1.91815824e+01  9.79226587e+01  1.55731398e+01  9.54879468e+01
  1.32183153e+01  6.09248449e+01  2.67011782e+01  1.17423836e+02
  1.48773331e+00  4.81464446e-01 -2.12148676e-01  8.84416275e-01
 -4.25061009e-02 -1.18865579e+00  4.21006310e+00  1.48535039e-01
  7.77947005e+00 -7.00409828e-01  1.89665085e+00 -2.89602762e-01
  6.04507132e-01  2.16117664e+00  4.19065093e+01 -1.23798345e+00
  7.94360030e+01  3.19454401e+02  7.96939510e+01  2.74428702e+02
  1.76217424e+01  1.13526563e+02  2.53575410e+01  1.14396692e+02
  1.39196397e+00 -1.43971523e-01  4.13849214e+00  2.09386324e-01
  7.99718453e+00 -1.26594769e+00  4.37363233e+01 -1.13394246e+00
 -2.40018398e+02 -1.02782465e+01 -1.39245790e+02]
<class 'numpy.ndarray'>
<class 'list'>
621
['0EA27ICBLF_1607.txt' '0EA27ICBLF_1608.txt']
102182

In [17]:
# Testing Code
user = users['UserID'][0]
files = get_user(user)
print(files)
tappy_data = extract_tappy_df(files)
print(tappy_data.head(10))
tappy_info = extract_features(tappy_data)
print(tappy_info)
print(len(tappy_info))

['0EA27ICBLF_1607.txt' '0EA27ICBLF_1608.txt']

/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (4,6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

       UserKey        Date     Timestamp Hand  Hold time Direction  \
0   0EA27ICBLF  2016-01-22  18:41:04.336    L      101.6        LL
1   0EA27ICBLF  2016-01-22  18:42:14.070    L       85.9        LL
2   0EA27ICBLF  2016-01-22  18:42:14.273    L       78.1        LL
3   0EA27ICBLF  2016-01-22  18:42:14.617    L       62.5        LL
6   0EA27ICBLF  2016-01-22  18:42:15.969    R       85.9        LR
7   0EA27ICBLF  2016-01-22  18:42:16.875    R       85.9        RR
8   0EA27ICBLF  2016-01-22  18:42:17.289    L       70.3        RL
9   0EA27ICBLF  2016-01-22  18:42:17.727    L      101.6        LL
12  0EA27ICBLF  2016-01-22  18:42:19.172    L       62.5        LL
13  0EA27ICBLF  2016-01-22  18:42:20.156    L       70.3        LL

    Latency time
0          234.4
1          437.5
2          210.9
3          359.4
6          195.3
7          359.4
8          429.7
9          406.3
12         406.3
13         289.1
[  82.16903976  263.5863773    81.94680999  277.61054092   74.67114757
  416.85633053   79.29456295  273.8646238    19.1815824    97.92265875
   15.57313984   95.48794685   13.21831533   60.92484493   26.70117819
  117.42383615   79.43600301  319.45440058   79.69395102  274.42870196
   17.62174244  113.52656298   25.35754097  114.39669187 -240.01839757
  -10.2782465  -139.24578961]
27

In [44]:
# Get data for all users with data
user_names = usersA['UserID']
NUM_FEATURES = 51
NUM_USERS = len(user_names)
new_data = np.zeros((NUM_USERS, NUM_FEATURES))
i = 0
for user in user_names: 
    files = get_user(user)
    tappy_data = extract_tappy_df(files)
    tappy_info = extract_features(tappy_data)
    new_data[i] = tappy_info
    i = i + 1

/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (4,6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (4,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (1,4,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/Users/k_vslv/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (4,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [37]:
print(user_names)
print(usersA['UserID'])
print(len(usersA))

0     0QAZFRHQHW
1     1HOEBIGASW
2     1XNJCXS3EY
3     3DIXPRIOSW
4     48DZPAJ5NS
         ...
82    YIA9DW5AGQ
83    YQSGN9BMVK
84    YWMIQIQND3
85    YYPKGX6B24
86    Z2UPVHHGBE
Name: UserID, Length: 87, dtype: object
0     0QAZFRHQHW
1     1HOEBIGASW
2     1XNJCXS3EY
3     3DIXPRIOSW
4     48DZPAJ5NS
         ...
82    YIA9DW5AGQ
83    YQSGN9BMVK
84    YWMIQIQND3
85    YYPKGX6B24
86    Z2UPVHHGBE
Name: UserID, Length: 87, dtype: object
87

In [45]:
# Data frame holding all the data
columns = ['LLHold', 'LLLatency','LRHold', 'LRLatency', 'RLHold', 'RLLatency', 'RRHold', 'RRLatency', 
           'LLHoldStd', 'LLLatencyStd','LRHoldStd', 'LRLatencyStd', 'RLHoldStd', 'RLLatencyStd', 'RRHoldStd', 'RRLatencyStd',
           'LLHoldSkew', 'LLLatencySkew','LRHoldSkew', 'LRLatencySkew', 'RLHoldSkew', 'RLLatencySkew', 'RRHoldSkew', 'RRLatencySkew',
           'LLHoldKurt', 'LLLatencyKurt','LRHoldKurt', 'LRLatencyKurt', 'RLHoldKurt', 'RLLatencyKurt', 'RRHoldKurt', 'RRLatencyKurt', 
           'LHold', 'LLatency', 'RHold', 'RLatency', 'LHoldStd', 'LLatencyStd', 'RHoldStd', 'RLatencyStd',
           'LHoldSkew', 'LLatencySkew', 'RHoldSkew', 'RLatencySkew', 'LHoldKurt', 'LLatencyKurt', 'RHoldKurt', 'RLatencyKurt',
           'LRHold_Diff', 'LLRRLatency_Diff', 'LRRLLatency_Diff']
user_info = pd.DataFrame(new_data, columns=columns)
dataAll = pd.concat([usersA, user_info], axis=1)
dataAll.head(30)
#dataAll.iloc[0]

,UserID,BirthYear,DA,DiagnosisYear,Gender,Impact,Levadopa,MAOB,Other,Parkinsons,...,LLatencySkew,RHoldSkew,RLatencySkew,LHoldKurt,LLatencyKurt,RHoldKurt,RLatencyKurt,LRHold_Diff,LLRRLatency_Diff,LRRLLatency_Diff
0,0QAZFRHQHW,1959.0,0,NaN,1,0,0,0,0,0,...,0.347884,7.402816,0.446804,0.805770,-0.699806,106.075763,-0.725689,-2.581164,40.979771,-18.540793
1,1HOEBIGASW,1944.0,0,NaN,0,0,0,0,0,0,...,-0.400556,0.239309,-0.208674,-0.233988,-0.775209,-0.109231,-1.327965,1.156507,-4.588235,64.026190
2,1XNJCXS3EY,1936.0,0,NaN,0,0,0,0,0,0,...,-0.685049,2.804074,-0.115531,0.797792,0.285031,23.790534,-0.215556,47.072756,25.711714,2.742036
3,3DIXPRIOSW,1936.0,0,NaN,0,0,0,0,0,0,...,-0.034457,0.264594,-0.364617,0.595533,-0.409263,0.520341,-0.042387,-18.904747,34.890816,74.204668
4,48DZPAJ5NS,1950.0,0,2010.0,0,1,0,0,1,1,...,0.284186,0.353481,-0.024474,5.019808,-0.741563,5.034476,-0.901017,-1.202048,-32.297880,14.376781
5,4XPHKKBXS6,NaN,0,NaN,0,0,0,0,0,0,...,-0.691740,0.490051,-0.468201,0.483930,-0.346225,1.474594,-0.245062,42.648060,-4.639493,-75.820623
6,5PQVTWULAC,1943.0,1,2009.0,1,1,0,0,1,1,...,0.680286,-0.131570,0.172752,7.843144,0.655488,0.804572,-0.396467,19.407512,-24.794478,24.435956
7,5USOYSDCXB,1941.0,0,2017.0,0,1,0,0,0,1,...,2.256335,-0.203109,2.077791,0.916242,8.984991,1.743974,8.934419,-1.629822,1.055860,-5.769697
8,6LB9FQABZQ,1956.0,0,NaN,1,0,0,0,0,0,...,2.145286,0.060631,1.933555,0.042916,5.269183,0.912507,3.890590,33.570270,2.387666,36.452778
9,81NEUZEBXI,NaN,0,NaN,0,0,0,0,0,0,...,0.094651,0.542473,-0.196737,1.269726,-0.994148,1.847934,-0.673033,1.545699,-10.011062,42.836106
10,8O9IAIA9L1,1947.0,0,NaN,1,0,0,0,0,0,...,2.198976,24.020617,2.120335,3.385447,7.640365,1161.233749,5.571300,-13.297996,2.363081,4.553453
11,9RCEHVGNCJ,1951.0,0,NaN,1,0,0,0,0,0,...,1.166440,-0.555675,1.360187,-0.754788,1.820339,1.506417,2.012809,6.611901,-10.160714,-23.957022
12,9ZRBC5WOZR,1943.0,0,2016.0,1,1,0,0,0,1,...,1.661018,1.425025,-0.512762,NaN,NaN,3.267518,-1.761120,48.133333,96.966667,-72.900000
13,AVNGRDUXE5,1948.0,0,NaN,1,0,0,0,0,0,...,0.713695,0.846842,1.124272,1.086535,-0.018553,2.065729,0.763148,35.606426,67.245007,-22.298242
14,AXXXXBBCCH,1949.0,0,NaN,1,0,0,0,0,0,...,0.625556,0.370267,1.201687,1.228290,-0.303483,-0.582935,1.136103,32.964444,16.974308,-26.514286
15,BENXJNDSC4,1960.0,0,NaN,1,0,0,0,0,0,...,-0.035282,-0.268481,-0.039308,6.757011,-0.878838,-0.091416,-0.998398,-13.036672,-10.996396,17.243333
16,BFXNVL50DC,1951.0,0,NaN,1,0,0,0,0,0,...,1.384384,1.006092,1.267562,-0.504994,2.051183,5.497084,1.718083,20.415546,0.660079,8.760001
17,CAXCJIKLYM,1946.0,0,2015.0,1,1,0,0,1,1,...,0.843726,0.751432,1.124383,368.039974,-0.063309,2.606670,0.998714,20.063484,27.613187,3.700107
18,COK8G1W7JY,NaN,0,NaN,0,0,0,0,0,0,...,0.775431,2.452191,0.662952,19.445994,0.697564,21.381284,-0.178154,-3.019265,-31.346989,32.042311
19,E0XRQVF05S,1936.0,0,NaN,1,0,0,0,0,0,...,0.146965,-1.190476,-0.088907,-0.305756,-1.338071,1.502936,1.433649,49.725000,NaN,128.160000
20,EF9XEFXPBN,1951.0,0,2016.0,1,1,0,1,0,1,...,0.469684,-0.337022,0.408427,0.649297,-0.584412,1.819932,-0.388161,13.747449,0.882046,8.878149
21,EMYGMAIB2L,1945.0,0,NaN,0,0,0,0,0,0,...,0.167238,2.997780,0.294554,29.540663,-0.562225,20.806973,-0.783101,24.175244,9.185906,5.102736
22,EZF9NAHLOU,1949.0,1,2015.0,0,1,0,0,0,1,...,0.487203,1.376966,0.317906,2.506715,-0.657268,2.068857,-0.612761,10.594085,-88.648916,111.393125
23,F56FSV2EP7,1961.0,0,NaN,0,0,0,0,0,0,...,0.040566,0.705636,0.107753,0.369657,-0.891219,1.897150,-0.882496,6.317119,-5.284786,-18.228599
24,F8KU8UP2SZ,1936.0,0,NaN,0,0,0,0,0,0,...,0.079991,0.095729,0.161917,3.933168,-0.576939,0.023946,-0.678595,15.765634,5.486450,-20.400226
25,FFNMFHHSZJ,1958.0,0,NaN,1,0,0,0,0,0,...,0.493144,-0.475350,0.414417,30.062973,-0.110051,0.242457,-0.036154,5.758823,-17.992207,11.306398
26,FX9KOOZRZL,1943.0,0,NaN,0,0,0,0,0,0,...,-0.867091,-0.334732,-0.721417,-1.045496,-0.554692,-1.298528,0.329135,4.290000,120.137500,-44.266667
27,G6OE5CXQPY,1952.0,0,NaN,0,0,0,0,0,0,...,2.052985,0.359136,1.865684,1.694897,6.696544,3.191397,4.440759,14.054674,-35.603742,23.990154
28,GEYWAGTINR,1929.0,0,NaN,0,0,0,0,0,0,...,0.322879,1.178742,0.691534,1.090954,-0.366886,4.477892,-0.426145,15.967162,73.440794,21.548862
29,GN1CUIPUTJ,1938.0,0,NaN,1,0,0,0,0,0,...,-0.398360,-0.091253,-0.906361,-1.883718,-1.882558,-1.832709,0.565024,-16.591667,66.433333,-100.006667

In [21]:
dataAll.columns

Index(['UserID', 'BirthYear', 'DA', 'DiagnosisYear', 'Gender', 'Impact',
       'Levadopa', 'MAOB', 'Other', 'Parkinsons', 'Sided', 'Tremors', 'UPDRS',
       'Length', 'LLHold', 'LLLatency', 'LRHold', 'LRLatency', 'RLHold',
       'RLLatency', 'RRHold', 'RRLatency', 'LLHoldStd', 'LLLatencyStd',
       'LRHoldStd', 'LRLatencyStd', 'RLHoldStd', 'RLLatencyStd', 'RRHoldStd',
       'RRLatencyStd', 'LHold', 'LLatency', 'RHold', 'RLatency', 'LHoldStd',
       'LLatencyStd', 'RHoldStd', 'RLatencyStd', 'LRHold_Diff',
       'LLRRLatency_Diff', 'LRRLLatency_Diff'],
      dtype='object')

In [46]:
dataAll.to_csv(r'ConvertedData-All.csv', index = False)

In [23]:
len(dataAll)

87

In [24]:
len(dataAll.index)

87

In [47]:
columns = ['LLHold', 'LLLatency','LRHold', 'LRLatency', 'RLHold', 'RLLatency', 'RRHold', 'RRLatency', 
           'LLHoldStd', 'LLLatencyStd','LRHoldStd', 'LRLatencyStd', 'RLHoldStd', 'RLLatencyStd', 'RRHoldStd', 'RRLatencyStd',
           'LLHoldSkew', 'LLLatencySkew','LRHoldSkew', 'LRLatencySkew', 'RLHoldSkew', 'RLLatencySkew', 'RRHoldSkew', 'RRLatencySkew', 
           'LHold', 'LLatency', 'RHold', 'RLatency', 'LHoldStd', 'LLatencyStd', 'RHoldStd', 'RLatencyStd',
           'LRHold_Diff', 'LLRRLatency_Diff', 'LRRLLatency_Diff']
dataSome = dataAll[columns]

In [48]:
dataSome.head()

,LLHold,LLLatency,LRHold,LRLatency,RLHold,RLLatency,RRHold,RRLatency,LLHoldStd,LLLatencyStd,...,LLatency,RHold,RLatency,LHoldStd,LLatencyStd,RHoldStd,RLatencyStd,LRHold_Diff,LLRRLatency_Diff,LRRLLatency_Diff
0,97.654140,406.716242,107.138017,411.718182,100.917949,430.258974,96.400784,365.736471,25.840600,162.606085,...,416.769161,101.628974,388.125956,24.686840,169.661724,38.443162,177.739911,-2.581164,40.979771,-18.540793
1,64.452941,390.058824,66.233333,600.433333,68.500000,536.407143,64.341176,394.647059,10.799197,199.162594,...,456.151613,65.124138,479.800000,11.988617,171.180139,11.873850,228.129262,1.156507,-4.588235,64.026190
2,143.399528,347.882547,105.325887,313.541489,163.700000,310.799454,106.208750,322.170833,51.115372,101.977747,...,330.702278,105.731801,317.509004,52.113723,101.744171,27.504959,91.199920,47.072756,25.711714,2.742036
3,144.314980,528.670445,180.632743,575.478761,156.391710,501.274093,159.277778,493.779630,42.482348,137.542548,...,520.973945,166.612462,521.840426,47.328593,139.653687,55.989508,163.028317,-18.904747,34.890816,74.204668
4,124.285207,300.323155,127.421731,335.508287,125.795492,321.131506,124.941855,332.621036,21.626193,81.749015,...,308.788745,126.101694,333.971404,21.223636,85.153594,20.245448,86.494091,-1.202048,-32.297880,14.376781

In [49]:
dataSome.to_csv(r'ConvertedData.csv', index = False)